// leartunity/resources/js/Components/Essentials/Header.vue
<script setup>
import Nav from '../../Shared/Nav.vue';
import NavLink from '../NavLink.vue';
</script>
<template>
    <header class="flex top-header container mx-auto mt-4">
      <div class="logo">
        <NavLink href="/"><h1>Leartunity.</h1></NavLink>
      </div>
      <Nav />
      </header>
</template>

// leartunity/resources/js/Components/Header.jsx
import { Link } from "@inertiajs/inertia-react"
import Nav from "../Layout/Nav"

export default function Header() {
    return (
        <header className="flex top-header container mx-auto mt-4">
        <div className="logo">
          <Link href="/"><h1>Leartunity.</h1></Link>
        </div>
        <Nav />
        </header>
    )
}
